### ISSUE TITLE
Minimal project example

### ISSUE THREAD

**Issue by tp** [paxan/heroku-buildpack-gb#1]
Would you mind expanding on the requirement of including the gb oneself through vendoring, or possibly better provide a minimal example project.

I am trying to find a way to attach dependencies without copying their whole sources into our repos.

**Comment by paxan** [comment]
@tp I've recently discovered [subtree](https://github.com/git/git/blob/master/contrib/subtree/git-subtree.txt) command. It works similarly to `merge -s subtree` but does all sorts of bookkeeping that you'd be doing by hand without `subtree` command.

I will work on adding a full example to README.

`gb` doesn't impose an opinion on how `src` and `vendor/src` get populated. I prefer using `git subtree` (opposite of your goal to find a way to attach dependencies without sources). Some organizations may prefer to write a special script that would retrieve vendored dependencies directly from their origin SCM systems, or from an internal archive. Git submodules may be used too (I wouldn't, but YMMV).
